# Generated by Django 4.0.3 on 2022-10-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_alter_accountvo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvo',
            name='is_active',
        ),
    ]
