# Generated by Django 4.0.3 on 2022-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_remove_accountvo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
